const items=[
{id:1,title:'Fall service launch',channel:'LinkedIn',priority:'High',status:'Needs review',owner:'Maya',due:'Today',next:'Approve claim wording',rationale:'Pricing language is verified; one performance sentence still needs a human claim check.',history:['Draft submitted · 9:10 AM','Brand review passed · 10:05 AM']},
{id:2,title:'October customer email',channel:'Email',priority:'High',status:'Waiting',owner:'Andre',due:'Today',next:'Receive legal response',rationale:'Customer testimonial permission is not yet confirmed.',history:['Copy review passed · Yesterday','Permission request sent · 8:30 AM']},
{id:3,title:'How-it-works carousel',channel:'LinkedIn',priority:'Medium',status:'Approved',owner:'Maya',due:'Oct 3',next:'Schedule publication',rationale:'Claims match source material and accessibility companion is complete.',history:['Accessibility revision · Sep 30','Approved by Maya · Oct 1']},
{id:4,title:'Retargeting headline set',channel:'Paid social',priority:'Medium',status:'Rejected',owner:'Jon',due:'Oct 4',next:'Rewrite two headlines',rationale:'Two variants imply guaranteed outcomes that the evidence does not support.',history:['Submitted · Oct 1','Rejected by Jon · Oct 2']},
{id:5,title:'Customer story draft',channel:'Website',priority:'Low',status:'Needs review',owner:'Priya',due:'Oct 5',next:'Verify quote attribution',rationale:'Narrative is ready; quoted language must be checked against the approved source.',history:['Draft submitted · Oct 1']},
{id:6,title:'Webinar reminder',channel:'Email',priority:'Low',status:'Approved',owner:'Andre',due:'Oct 6',next:'Queue send',rationale:'Event facts, links, audience, and unsubscribe requirements were checked.',history:['Link check passed · Oct 2','Approved by Andre · Oct 2']}
];
const q=document.querySelector('#queue'),search=document.querySelector('#search'),status=document.querySelector('#status'),owner=document.querySelector('#owner'),empty=document.querySelector('#empty'),detail=document.querySelector('#detail'),notice=document.querySelector('#notice');
[...new Set(items.map(x=>x.owner))].sort().forEach(x=>owner.insertAdjacentHTML('beforeend',`<option>${x}</option>`));
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function render(){const term=search.value.trim().toLowerCase();const list=items.filter(x=>(status.value==='all'||x.status===status.value)&&(owner.value==='all'||x.owner===owner.value)&&(!term||Object.values(x).join(' ').toLowerCase().includes(term)));q.innerHTML=list.map(x=>`<tr tabindex="0" data-id="${x.id}" aria-label="Open ${esc(x.title)} details"><td><b>${esc(x.title)}</b></td><td>${esc(x.channel)}</td><td>${esc(x.priority)}</td><td><span class="badge">${esc(x.status)}</span></td><td>${esc(x.owner)}</td><td>${esc(x.due)}</td><td>${esc(x.next)}</td></tr>`).join('');empty.hidden=list.length>0;document.querySelector('#resultCount').textContent=`${list.length} of ${items.length} items`;document.querySelector('#needsCount').textContent=items.filter(x=>x.status==='Needs review').length;document.querySelector('#waitingCount').textContent=items.filter(x=>x.status==='Waiting').length;document.querySelector('#decidedCount').textContent=items.filter(x=>['Approved','Rejected'].includes(x.status)).length;notice.textContent=`Showing ${list.length} queue items.`}
function show(id){const x=items.find(i=>i.id===Number(id));detail.innerHTML=`<h2>${esc(x.title)}</h2><div class="detail-grid"><div><h3>Decision rationale</h3><p>${esc(x.rationale)}</p><p><b>Next action:</b> ${esc(x.next)}</p></div><div><h3>Decision history</h3><ol class="history">${x.history.map(h=>`<li>${esc(h)}</li>`).join('')}</ol></div></div>`}
[search,status,owner].forEach(el=>el.addEventListener('input',render));document.querySelector('#reset').addEventListener('click',()=>{search.value='';status.value='all';owner.value='all';render();search.focus()});q.addEventListener('click',e=>{const r=e.target.closest('tr');if(r)show(r.dataset.id)});q.addEventListener('keydown',e=>{const r=e.target.closest('tr');if(r&&(e.key==='Enter'||e.key===' ')){e.preventDefault();show(r.dataset.id)}});render();
